Update zbxTelegram.py
xxsokolov/Zabbix-Notification-Telegram pull request #49
Opened 2023-01-26 06:27 UTC by ozaryx

Add set token from command args. Token from args has high priority. This will allow to configure telegram bot token directly from zabbix.

2023-01-26 13:33 UTC, xxsokolov commented on zbxTelegram.py
>  bot = telebot.TeleBot(tg_token)
bot = telebot.TeleBot(args.token if args.token else tg_token)

2023-01-26 13:34 UTC, xxsokolov requested changes
change

2023-01-27 10:12 UTC, ozaryx commented on zbxTelegram.py
>  bot = telebot.TeleBot(tg_token)
Ок. It's look better
bot = telebot.TeleBot(args.token if args.token else tg_token)

2023-01-27 10:24 UTC, closed without merging

2023-01-27 10:25 UTC, ozaryx commented
Make another PR